apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-datasource
  namespace: prometheus
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        isDefault: true
        url: http://loki-distributed-gateway.prometheus.svc.cluster.local:80
        basicAuth: true
        basicAuthUser: admin
        secureJsonData:
          basicAuthPassword: "<YOUR-PASSWORD-HERE>"
        jsonData:
          maxLines: 1000